# Canonical Data Schema for Financial Snapshots
# Version: 1
# Date: 2026-02-19
# Purpose: Define the standard column structure for CSV snapshots stored in dados/

schema_version: 1

metadata:
  description: "Canonical schema for financial market data snapshots"
  versioning_policy: "Semantic versioning - increment schema_version for breaking changes"
  last_updated: "2026-02-19"
  owner: "Data Engineering Team"

columns:
  - name: ticker
    type: string
    nullable: false
    description: "Stock ticker symbol (e.g., PETR4, VALE3)"
    constraints:
      - "Must be uppercase alphanumeric"
      - "Max length 10 characters"
    example: "PETR4"

  - name: date
    type: date
    format: "YYYY-MM-DD"
    nullable: false
    description: "Trading date in ISO 8601 format"
    constraints:
      - "Must be valid date"
      - "Format: YYYY-MM-DD"
    example: "2024-01-15"

  - name: open
    type: float
    nullable: true
    description: "Opening price for the trading day"
    constraints:
      - "Must be >= 0"
      - "Precision: 2 decimal places recommended"
    example: "28.50"

  - name: high
    type: float
    nullable: true
    description: "Highest price during the trading day"
    constraints:
      - "Must be >= 0"
      - "Must be >= open and close"
    example: "29.75"

  - name: low
    type: float
    nullable: true
    description: "Lowest price during the trading day"
    constraints:
      - "Must be >= 0"
      - "Must be <= open and close"
    example: "28.25"

  - name: close
    type: float
    nullable: true
    description: "Closing price for the trading day"
    constraints:
      - "Must be >= 0"
      - "Precision: 2 decimal places recommended"
    example: "29.10"

  - name: adj_close
    type: float
    nullable: true
    description: "Adjusted closing price (accounts for splits, dividends)"
    constraints:
      - "Must be >= 0"
      - "Precision: 2 decimal places recommended"
    example: "29.10"

  - name: volume
    type: integer
    nullable: true
    description: "Trading volume (number of shares traded)"
    constraints:
      - "Must be >= 0"
    example: "15420000"

  - name: source
    type: string
    nullable: false
    description: "Data source identifier (e.g., yfinance, b3-api)"
    constraints:
      - "Must be lowercase alphanumeric with hyphens"
      - "Max length 50 characters"
    example: "yfinance"

  - name: fetched_at
    type: datetime
    format: "ISO8601"
    nullable: false
    description: "UTC timestamp when data was fetched from the provider"
    constraints:
      - "Must be valid ISO 8601 datetime"
      - "Must be in UTC timezone"
      - "Format: YYYY-MM-DDTHH:MM:SSZ"
    example: "2024-01-15T18:30:45Z"

  - name: raw_checksum
    type: string
    nullable: true
    description: "SHA256 checksum of raw provider payload for auditability"
    constraints:
      - "Must be valid SHA256 hex string (64 characters)"
      - "Lowercase hexadecimal"
    example: "a3f2c5d8e9b1234567890abcdef01234567890abcdef01234567890abcdef0123"

  - name: Return
    type: float
    nullable: true
    description: "Calculated daily return (required by existing consumers)"
    constraints:
      - "Can be negative (losses) or positive (gains)"
      - "Typically calculated as (close - prev_close) / prev_close"
    example: "0.0234"
    note: "Legacy column - maintained for backward compatibility with src/retorno.py"

# Versioning and Migration Strategy
versioning:
  current_version: 1
  migration_policy:
    minor_changes:
      - "Adding new optional columns (nullable=true)"
      - "Adding new constraints that don't break existing data"
      - "Adding metadata or documentation fields"
      - "These do NOT increment schema_version"
    
    breaking_changes:
      - "Removing columns"
      - "Renaming columns"
      - "Changing column types"
      - "Making nullable columns non-nullable"
      - "Adding non-nullable columns without defaults"
      - "These MUST increment schema_version"
  
  migration_notes:
    - version: 1
      date: "2026-02-19"
      description: "Initial canonical schema definition"
      changes:
        - "Established baseline column structure"
        - "Included legacy Return column for backward compatibility"
        - "Defined versioning and migration policies"

# Validation Rules
validation:
  required_columns:
    - ticker
    - date
    - source
    - fetched_at
  
  optional_columns:
    - open
    - high
    - low
    - close
    - adj_close
    - volume
    - raw_checksum
    - Return
  
  business_rules:
    - "high >= low for any given row"
    - "high >= open and high >= close (when all present)"
    - "low <= open and low <= close (when all present)"
    - "date must be in the past or today (no future dates)"
    - "fetched_at must be >= date (can't fetch historical data before it existed)"

# File Format Specifications
file_format:
  type: "CSV"
  encoding: "UTF-8"
  delimiter: ","
  header: true
  quoting: "minimal"
  decimal_separator: "."
  date_format: "YYYY-MM-DD"
  datetime_format: "ISO8601"
  null_representation: ""
  
# Storage Location
storage:
  snapshot_directory: "dados/"
  example_directory: "dados/examples/"
  checksum_extension: ".checksum"
  naming_convention: "{ticker}_snapshot.csv or {ticker}_{date_range}.csv"
