---
schema_version: 1
description: "Esquema canônico para snapshots CSV gerados pelo pipeline. Campos, tipos e flags de nulidade."
columns:
  - name: ticker
    type: string
    nullable: false
    note: "Símbolo do ativo, ex.: PETR4.SA"
  - name: date
    type: date
    format: YYYY-MM-DD
    nullable: false
    note: "Data da observação (ISO date)"
  - name: open
    type: number
    nullable: true
  - name: high
    type: number
    nullable: true
  - name: low
    type: number
    nullable: true
  - name: close
    type: number
    nullable: true
  - name: adj_close
    type: number
    nullable: true
    note: "Adjusted close quando disponível"
  - name: volume
    type: integer
    nullable: true
  - name: source
    type: string
    nullable: false
    note: "Identificador do provider (ex.: yfinance)"
  - name: fetched_at
    type: datetime
    format: ISO8601
    nullable: false
    note: "Timestamp UTC quando os dados foram buscados"
  - name: raw_checksum
    type: string
    nullable: true
    note: "SHA256 hex do payload bruto (para auditoria)"
metadata:
  recommended_snapshot_filename: "snapshots/<ticker>-YYYYMMDD.csv"
  required_headers: [ticker, date, open, high, low, close, adj_close, volume, source, fetched_at]
  versioning: |
    - Minor changes: adicionam colunas opcionais (não-break)
    - Breaking changes: renomeiam ou removem colunas existentes (require migration and bump schema_version)
  migration_notes: "Documentar mudança em docs/schema.md e atualizar schema_version"
---
