"""Orquestração de ingestão de snapshots com cache e ingestão incremental.

O bloqueio por ticker usado internamente (via :func:`src.ingest.ticker_lock`) é
aplicado apenas **no mesmo processo**. Se você deseja garantir exclusão
mútua entre dois invocados distintos do CLI, será necessário substituir o
mecanismo por um lock baseado em arquivo ou similar — o código atual não
faz essa sincronização entre processos.

Esta implementação foi adicionada na story 1.10 e dá suporte aos critérios
aceitação:

* cache de snapshot com TTL configurável e opção ``--force-refresh``
* ingestão incremental apenas de linhas novas/alteradas (com base em
  ``raw_checksum``) para reduzir trabalho no banco de dados
* validação de checksum antes de processar
* logs estruturados sobre decisões de cache e contagem de registros
* funções facilmente testáveis e CLI (ver `src.main`
  comando ``ingest-snapshot``)

A lógica é suficientemente simples para ser aplicada em arquivos locais
(`dados/`) e pode ser estendida posteriormente para armazenamentos remotos
(se a chave de cache passar a ser um identificador não ligado ao path).
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional, Union

import pandas as pd

from src.db_client import DatabaseClient, DefaultDatabaseClient
from src.ingest import cache as _cache
from src.ingest.pipeline import rows_to_ingest
from src.ingest.ticker_lock import lock_ticker
from src.utils.checksums import sha256_file

logger = logging.getLogger(__name__)

# defaults -----------------------------------------------------------
DEFAULT_TTL = float(os.getenv("SNAPSHOT_TTL", "86400"))  # 1 day in seconds
# may be fractional for tests
DEFAULT_CACHE_FILE = os.getenv("SNAPSHOT_CACHE_FILE") or "dados/snapshot_cache.json"


# helpers ------------------------------------------------------------

def _read_checksum(path: Path) -> str:
    """Return the SHA256 checksum for ``path``.

    If a companion ``.checksum`` file exists it will be compared against the
    computed value; um mismatch causa erro para evitar ingestões silenciosas
de arquivos corrompidos.
    """
    actual = sha256_file(path)
    check_path = path.with_name(f"{path.name}.checksum")
    if check_path.exists():
        expected = check_path.read_text().strip()
        if expected != actual:
            raise ValueError(
                f"checksum mismatch for {path}: expected {expected}, got {actual}"
            )
    return actual


def _normalize_df(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure the DataFrame has a ``date`` column and is timezone-naive.

    The downstream DB layer requires either a DatetimeIndex or a ``date``
    column to convert to index; this helper also drops any unnamed index that
    may have been generated by ``read_csv``.
    """
    df = df.copy()
    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"]).dt.tz_localize(None)
    else:
        # try to use index if it looks like dates
        if isinstance(df.index, pd.DatetimeIndex):
            df = df.reset_index().rename(columns={df.index.name or "index": "date"})
        else:
            raise ValueError(
                "snapshot DataFrame must have a 'date' column or datetime index"
            )
    return df


def _compute_changes(
    df: pd.DataFrame,
    ticker: str,
    repo: DatabaseClient,
    conn: Optional[Any] = None,
    db_path: Optional[str] = None,
) -> pd.DataFrame:
    """Return subset of ``df`` that is new or modified compared to DB.

    This implementation now delegates to the shared helper in
    :mod:`src.ingest.pipeline`.  The helper already normalizes the frame and
    guarantees consistent behaviour with :func:`ingest_from_snapshot`.

    ``df`` must already be normalized (see :func:`_normalize_df`).
    """
    # fetch existing rows for the given date range; helper will handle the
    # diff logic once the frame is prepared.
    start = df["date"].min()
    end = df["date"].max()
    if hasattr(start, "strftime"):
        start = start.strftime("%Y-%m-%d")
    if hasattr(end, "strftime"):
        end = end.strftime("%Y-%m-%d")

    existing = repo.read_prices(
        ticker,
        start=start,
        end=end,
        conn=conn,
        db_path=db_path,
    )

    rows = rows_to_ingest(df, existing)
    return rows.reset_index(drop=False)


# public API ---------------------------------------------------------

def ingest_snapshot(
    snapshot_path: Union[str, Path],
    ticker: Optional[str] = None,
    *,
    db_client: Optional[DatabaseClient] = None,
    conn: Optional[Any] = None,
    db_path: Optional[str] = None,
    force_refresh: bool = False,
    ttl: Optional[float] = None,
    cache_file: Optional[Union[str, Path]] = None,
) -> Dict[str, Any]:
    """Processa um snapshot CSV e faz ingest incremental usando cache.

    Parameters
    ----------
    snapshot_path:
        Caminho para o arquivo CSV que contém o snapshot. Deve haver uma
        coluna ``date`` ou o índice deve ser datetime-like.  A presença da
        coluna ``ticker`` permite omitir o argumento ``ticker``.
    ticker:
        Identificador do ativo; necessário se o CSV não contiver a coluna
        correspondente.
    db_client:
        Cliente opcional para abstração de acesso ao banco.  Por padrão
        instanciamos ``DefaultDatabaseClient``.
    conn:
        Conexão SQLite opcional a ser usada tanto para leitura quanto para
        escrita (útil em testes).
    db_path:
        Caminho para o banco quando ``conn`` não é fornecido.
    force_refresh:
        Ignorar cache mesmo que o snapshot já tenha sido processado recentemente.
    ttl:
        Tempo em segundos (pode ser fracionário nos testes) a partir do último
        processamento em que um cache é considerado válido.  ``None`` desativa
        expiração.  Se nenhum valor for passado, o valor de ambiente
        ``SNAPSHOT_TTL`` (ou 86400s) é usado.
    cache_file:
        Caminho para o arquivo JSON usado como cache.  Padrão:
        ``dados/snapshot_cache.json`` ou ``SNAPSHOT_CACHE_FILE``.

    Returns
    -------
    dict
        Um dicionário com os campos ``cached`` (bool), ``processed_rows`` e
        ``skipped_rows``.
    """
    snapshot_path = Path(snapshot_path)
    if not snapshot_path.exists():
        raise FileNotFoundError(f"snapshot not found: {snapshot_path}")

    # TTL may be fractional (tests) and DEFAULT_TTL is already a float; ensure
    # the returned value is a float so callers can compare using <= reliably.
    ttl = float(DEFAULT_TTL) if ttl is None else float(ttl)
    cache_file = Path(cache_file or DEFAULT_CACHE_FILE)

    checksum = _read_checksum(snapshot_path)
    key = str(snapshot_path.resolve())

    cache = _cache.load_cache(cache_file)
    entry = cache.get(key)
    if (
        entry
        and not force_refresh
        and entry.get("sha256") == checksum
        and _cache.entry_is_fresh(entry, ttl)
    ):
        logger.info("ingest_snapshot cached", extra={"snapshot": key})
        return {"cached": True, "processed_rows": 0, "skipped_rows": 0}

    # Need to actually load the CSV and potentially write to DB
    df = pd.read_csv(snapshot_path)
    df = _normalize_df(df)

    if ticker is None:
        if "ticker" in df.columns:
            unique = df["ticker"].unique()
            if len(unique) == 1:
                ticker = unique[0]
            else:
                # snapshot contains more than one ticker; refuse to guess
                raise ValueError(
                    f"snapshot contains multiple tickers: {unique.tolist()}"
                )
        else:
            raise ValueError("ticker argument required when snapshot lacks column")

    # at this point we guarantee a string value for ticker, but the type
    # checker still sees Optional[str].  narrow with an assertion so callers
    # (and Pylance) know it is safe to pass to ``lock_ticker``.
    assert isinstance(ticker, str), "ticker must be a string"

    if db_client is None:
        db_client = DefaultDatabaseClient()

    with lock_ticker(ticker):
        changed = _compute_changes(df, ticker, db_client, conn=conn, db_path=db_path)
        processed = len(changed)
        skipped = len(df) - processed

        if processed > 0:
            db_client.write_prices(changed, ticker, conn=conn, db_path=db_path)

        # update cache even if nothing was processed, so subsequent calls
        # within the TTL will skip. Use the same checksum we validated above.
        cache[key] = {
            "sha256": checksum,
            "processed_at": datetime.now(timezone.utc).isoformat(),
        }
        _cache.save_cache(cache_file, cache)

    logger.info(
        "ingest_snapshot",
        extra={
            "snapshot": key,
            "processed_rows": processed,
            "skipped_rows": skipped,
        },
    )

    return {"cached": False, "processed_rows": processed, "skipped_rows": skipped}


__all__ = ["ingest_snapshot"]
